### ISSUE TITLE
Nginx 404 with fof/sitemap

### ISSUE THREAD

**Issue by LittleSheep2010** [mondediefr/docker-flarum#103]
Can I use the sitemap plugin with this?
I access it and get 404 error

My proxychain:
`docker(LocalServer)` -> `Nginx(LocalServer)` -> `Frpc(LocalServer)` -> `Frps` -> `Nginx`

My forum url: [https://forum.smartsheep.club](https://forum.smartsheep.club)
I can sure the remote server configure is right, because I access it use the localhost and it is same 404 error
Any, question or suggest?

The [description](https://discuss.flarum.org/d/14941-fof-sitemap) said I need change the nginx configure, and how I change it? I need add this things:
```
location = /sitemap.xml {
    try_files $uri $uri/ /index.php?$query_string;
}
```

Thanks.

**Comment by Magicalex** [comment]
https://github.com/mondediefr/docker-flarum#custom-vhost-flarum-nginx
