### ISSUE TITLE
replace php7 (alpine) by wonderfall/nginx-php

### ISSUE THREAD

**Issue by Magicalex** [mondediefr/docker-flarum#11]
@hardware @Wonderfall
https://github.com/Wonderfall/dockerfiles/blob/master/nginx-php/Dockerfile

**Comment by hardware** [comment]
Je sais pas si c'est vraiment utile depuis qu'on bloque une version stable. En plus ça ajoute une surcouche à maintenir et à build manuellement puisque certaines extensions php requises par flarum ne sont pas dans wonderfall/nginx-php.

**Comment by Wonderfall** [comment]
Actuellement l'image utilise `testing` : https://github.com/mondediefr/docker-flarum/blob/master/Dockerfile#L10
Quelles sont ces extensions ?

**Comment by hardware** [comment]
Ok pourquoi pas alors. ça change quoi au niveau de l'organisation de l'image docker ? J'ai juste à mettre ` `FROM wonderfall/nginx-php` et à supp les paquets php7* et nginx ?

**Comment by Wonderfall** [comment]
Entre autres il faut faire ça déjà, ensuite il faut placer quelques fichiers de configuration aux bons endroits, pour ça je recommande de réunir les directives COPY en  une seule qui fasse `COPY rootfs /`, et donc de tout mettre dans un dossier `rootfs` qui respecte l'arborescence depuis la racine.

- `/rootfs/nginx/sites-enabled/nginx.conf` : mettre le block `server` seulement et pas besoin d'y mettre `client_max_body` puisque c'est déjà dans serveur. Utiliser `fastcgi_pass unix:/php/run/php-fpm.sock` et ` include /nginx/conf/fastcgi_params` pour fastcgi.
- Pas besoin de mettre le `php-fpm.conf` custom. 
- Remplacer `php7` par `php` tout court dans les scripts.
- Mettre la conf opcache dans `/php/conf.d/opcache.ini`.

Par contre il faut placer ça dans `run.sh` : 

```
sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /nginx/conf/nginx.conf /php/etc/php-fpm.conf \
       -e "s/<MEMORY_LIMIT>/$MEMORY_LIMIT/g" /php/etc/php-fpm.conf
```

Donc ajouter les variables d'environnement : 
- `ENV UPLOAD_MAX_SIZE=50M`
- `ENV MEMORY_LIMIT=` à vous de voir, dépend de la machine...

**Comment by Wonderfall** [comment]
Voilà j'ai mis à jour les instructions pour la migration, si je vois un autre truc je mettrai à jour.

**Comment by hardware** [comment]
Merci pour les instructions, ça marche bien en local. Je vais maintenant tester en prod.

**Comment by hardware** [comment]
Bon bah ça a marché en prod du premier coup, ça c'est de l'image de qualité :+1: 
Merci encore @Wonderfall.

**Comment by Wonderfall** [comment]
Cool si ça marche bien alors. 😇

**Comment by Wonderfall** [comment]
Par contre comme dit dans mon précédent post, plus besoin de `/etc/s6.d` parce que la même chose est déjà présente d'origine dans l'image : https://github.com/mondediefr/docker-flarum/tree/master/rootfs/etc/s6.d

**Comment by hardware** [comment]
Effectivement, j'ai oublié ça. J'aime bien cette organisation, c'est plus propre. Tu pourras faire des tags pour les versions de php à l'occasion, si un jour il y a un pb de compatibilité, ça pourrait servir.

**Comment by Wonderfall** [comment]
Oui j'en ferai pour les versions majeures et intermédiaires. Niveau maintenance l'image est rebuild une fois par semaine automatiquement et si jamais je suis absent et qu'il faut mettre à jour, @xataz et toi avez (depuis un moment) accès à mon repo en écriture.

**Comment by Wonderfall** [comment]
J'ai mis un tag `7.1` pour PHP 7.1. D'ailleurs il y a eu une mise à jour il y a 2 jours en 7.1.5.
En train d'être build : https://hub.docker.com/r/wonderfall/nginx-php/builds/byzewxitlnko76vne6sou7n/
