### ISSUE TITLE
Can the image support config composer repo mirror url?

### ISSUE THREAD

**Issue by jaggerwang** [mondediefr/docker-flarum#13]
Right now, I use `docker exec -ti ynz-forum_flarum_1 extension config repo.packagist composer https://packagist.phpcomposer.com` to config mirror url in China. But this config will reset when restart container.

**Comment by hardware** [comment]
```
/mnt/docker/flarum/extensions/composer.repositories.txt

my_private_repo|{"type":"path","url":"extensions/*/"}
my_public_repo|{"type":"vcs","url":"https://github.com/my/repo"}
```

**Comment by jaggerwang** [comment]
Nor working!

```
> cat composer.repositories.txt
packagist|{"type":"path","url":"https://packagist.phpcomposer.com"}
```

Got the following error.
![image](https://user-images.githubusercontent.com/1255011/28713157-943797ca-73c0-11e7-80ac-9cd5b7f3de76.png)

**Comment by hardware** [comment]
Sorry, wrong type :

`packagist|{"type":"composer","url":"https://packagist.phpcomposer.com"}`

**Comment by jaggerwang** [comment]
Worked! Thanks!
