### ISSUE TITLE
It is impossible to use this image from scratch

### ISSUE THREAD

**Issue by Id2ndR** [mondediefr/docker-flarum#15]
There is a lot of things to do to be able to use this image from scratch :
- remove custom error page 500 that prevent you to understand troubles : `docker-compose exec flarum sh`; remove line 12 in _/nginx/sites-enabled/flarum.conf_; wait for the chown to or reload nginx if allready started with `kill -HUP 13`
- database :
 - use mysql 5 until https://github.com/flarum/core/issues/1211 is resolved
 - if the was a failure with the database, drop it since schema is already created : `docker-compose exec mariadb mysql -pxxxxxxxx -e 'drop database flarum; create database flarum;'`
- open your browser and fulfil the form
- the database will be initialized, and there will be 2 new files : /flarum/app/assets/rev-manifest.json and /flarum/app/config.php

You will then a _504 Gateway Time-out_ from nginx (flarum container), because php-fpm process doesn't end.

**Comment by hardware** [comment]
Please, learns to expose a problem or open a pull request if you want to improve this docker image.
