### ISSUE TITLE
Add support when using Dockerfile instead of docker-compose.yml

### ISSUE THREAD

**Issue by wildan3105** [mondediefr/docker-flarum#22]
I'm having an issue when creating container using `Dockerfile` for `flarum` and `mariadb` since there's no official documentation about this. I tried to pass environment variables described in `docker-compose.yml` as arguments, but it didn't work. Thanks

**Comment by hardware** [comment]
```
docker build -t mondedie/docker-flarum https://github.com/mondediefr/flarum.git#master
```
