### ISSUE TITLE
error - 404 page not found

### ISSUE THREAD

**Issue by lpt2007** [mondediefr/docker-flarum#28]
I installed like this:

pull image:
docker pull mondedie/docker-flarum

run:
docker-compose up -d

When I try to visit the forum page: http://my-ip I get error: 404 page not found

I miss something or what?

**Comment by Magicalex** [comment]
Please can you post your docker-compose?

**Comment by lpt2007** [comment]
Hi there is my docker-compose.yml

version: "3"

services:
  flarum:
    image: mondedie/docker-flarum:0.1.0-beta.7.1-stable
    container_name: flarum
    labels:
      - traefik.enable=true
      - traefik.backend.port=8888
      - traefik.frontend.rule=Host:192.168.0.199
    environment:
      - FORUM_URL=http://192.168.0.199
      - DB_PASS=test
    volumes:
      - /mnt/docker/flarum/assets:/flarum/app/assets
      - /mnt/docker/flarum/extensions:/flarum/app/extensions
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=test
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql

  traefik:
    image: traefik
    container_name: traefik
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker/traefik.toml:/traefik.toml:ro
