### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by kkxxxxxxx** [mondediefr/docker-flarum#32]
This forum is down for maintenance.

https://discuss.flarum.org/d/17496-flarum-0-1-0-beta-7-2-released/3

fix: need to access http://yourdomain.com/admin and enter the database password

**Comment by Magicalex** [comment]
Indeed for upgrade flarum you need to update database via http://yourdomain.com/admin

https://github.com/mondediefr/docker-flarum#upgrade-from-v010-beta6
