### ISSUE TITLE
Add instructions for running nginx

### ISSUE THREAD

**Issue by divan** [mondediefr/docker-flarum#37]
Is there any instruction on running proxy or everyone is expected to figure out on their own?

Maybe providing working default setup (nginx, for example) will do well for 80% of users, and 20% who want to use their own setup (Apache, Caddy, etc) will always be able to change and replace the docker-compose config.

The idea of docker-compose is to lower configuration and running pain to the virtually zero level, after all. And currently every single user has to figure out how to setup and configure the proxy, and that can take hours of googling and guesswork.

What do you think?

**Comment by divan** [comment]
Okay, after carefully reviewing setup, I realized that actually reverse proxy is not needed for running things locally. It's just when you read installation instructions, you tend to follow each step without questioning it.

Do you mind over PR with updated README, that can make this point clearer?

**Comment by Magicalex** [comment]
> Do you mind over PR with updated README, that can make this point clearer?

yes of course
