### ISSUE TITLE
how to install extension by docker-flarum

### ISSUE THREAD

**Issue by 451518849** [mondediefr/docker-flarum#39]
when i use docker to install an extension ,it always fails or automatically pauses，like this：
root@host:~# docker exec -ti flarum extension require flagrow/bazaar
    1/9:	http://repo.packagist.org/p/provider-archived$9a42801f781ce21eae36dc39736d760c309f5e4895a9c3de0d07e547d6c7b2be.json
    2/9:	http://repo.packagist.org/p/provider-latest$745ba4033a7c59605c2758c585d28147bbe18bd64e0c6f001a3d6e439be8e1ab.json
    3/9:	http://repo.packagist.org/p/provider-2018$13ad67b640ef9ef820262c374b7301afd52d55afa66907b31c82fa5405fdcd1e.json
    4/9:	http://repo.packagist.org/p/provider-2018-04$3402bb729d582639141d90698cc04981ed6a7d5aaebf46899f215ed0972cd0f6.json
    5/9:	http://repo.packagist.org/p/provider-2018-10$887152be6c120fe66381e72c195c6c53c54a553530f0cede132e2ec56853476d.json
    6/9:	http://repo.packagist.org/p/provider-2016$6b4efdc0920a04abc04569a25f56d1ce3fc8f6c4a4e446fb2f65623efd75be82.json
    7/9:	http://repo.packagist.org/p/provider-2017$c12832bd4aeee53c3d87ef3a67bda911d30e58e76bc7357f3639521f6949c6e1.json

can you tell me how to solve this problem ?

**Comment by Magicalex** [comment]
You can't install extension via bazaar see #21 
Please, use composer.
