### ISSUE TITLE
Update flarum to beta.9

### ISSUE THREAD

**Issue by jslirola** [mondediefr/docker-flarum#40]
Could you update the flarum docker image to version v0.1.0-beta.8.2?

This is the release: https://github.com/flarum/core/releases/tag/v0.1.0-beta.8.2

Thank you.

**Comment by Magicalex** [comment]
Beta 9 is release. I upgrade this image this week.

**Comment by kkxxxxxxx** [comment]
many extensions urgent need beta 9

**Comment by Moskito99** [comment]
Still beta.8.1 :-(
