### ISSUE TITLE
Do not update extensions on container restart

### ISSUE THREAD

**Issue by zullin** [mondediefr/docker-flarum#41]
Hello!
Is it possible not to update extensions every time the container is restarted? What is it for? When there are many extensions, restarting takes a long time. With 12 extensions step "Updating dependencies (including require-dev)" takes 40 seconds.

**Comment by Magicalex** [comment]
You can't right now. Problem is the extension are downloaded in the vendor folder.

**Comment by zullin** [comment]
Ok, I improved the situation by increasing the amount of RAM up to 1024MB.
