### ISSUE TITLE
Image removed from Docker Hub

### ISSUE THREAD

**Issue by thorthur** [mondediefr/docker-flarum#46]
Hello,

Just found out today that your image is no longer available.

```
Pulling flarum (mondedie/docker-flarum:0.1.0-beta.8.1-stable)...
pull access denied for mondedie/docker-flarum, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Furthermore, https://hub.docker.com/r/mondedie/docker-flarum leads to a 404.

**Comment by Hydrog3n** [comment]
Woo thank for this info :/ @Magicalex

**Comment by Hydrog3n** [comment]
Ok it's https://hub.docker.com/r/mondedie/flarum now ;)

**Comment by thorthur** [comment]
Thanks!
Congrats for the very quick reply.

**Comment by Magicalex** [comment]
Sorry for this change :sweat_smile:

We build the docker image with buildx and github action now.
