### ISSUE TITLE
Ability to install custom php extensions (or apk packages in general)

### ISSUE THREAD

**Issue by askvortsov1** [mondediefr/docker-flarum#51]
Perhaps we should add a way for people to add apk packages they would like to be installed, similarly to how there's a way to specify extensions that should be installed on container initialization

**Comment by Magicalex** [comment]
I don't know... Do you have a suggestion?

**Comment by PixiBixi** [comment]
I think it can be easy with an environment variable, but what’s the point?

**Comment by askvortsov1** [comment]
After giving this some more thought, I think that the best approach is:

1. To include PHP extensions and other resources that are clearly needed (like iconv)
2. To encourage people in the documentation to use this image as a base  for other images where they can include packages needed by their use case

I'm not sure that my initial thought of providing a utility to manage this is warranted or productive

**Comment by PixiBixi** [comment]
If people want to use this image as a source image, they can re-write their own Dockerfile using this one as base-image (directive FROM)

For the first point, you've totally right

**Comment by askvortsov1** [comment]
Alright, closing as not really actionable.

**Comment by Magicalex** [comment]
@askvortsov1 This is a good solution for you? https://github.com/mondediefr/docker-flarum/commit/052b6cc755867f05047d7ce508c92b786bfb1edf

**Comment by askvortsov1** [comment]
This is great, thank you very much!
