### ISSUE TITLE
After docker-compose down and docker-compose up only bad gateway, no debug, no LOG_TO_STDOUT

### ISSUE THREAD

**Issue by Braintelligence** [mondediefr/docker-flarum#57]
Hi there, title says most of the problem.

I run flarum with traefik. Installation went fine. I also installed some extensions. Then I wanted to test persistence by going `docker-compose down` and `docker-compose up -d` but I only get bad gateway now, even though `DEBUG=true` and `LOG_TO_STDOUT=true` (there are no logs in /var/log/nginx or /var/log/php7).

PHP_EXTENSIONS also seems to do weird things, brotli gets installed in the beginning but then it also says
```
[InvalidArgumentException]
Could not find package brotli[NAME_OF_FIRST_INSTALLED_FLARUM_EXTENSION_HERE].

Did you mean one of these?
...
```

If I move the first installed flarum extension from the list down one line it instead says "Could not find package brotli".

Any idea why I get bad gateway and debugging or logging just doesn't happen?

EDIT: At the ~15th try for some reason after 10 minutes of waiting the site worked. I'll try if it really is about waiting.

EDIT2: So if I keep PHP_EXTENSIONS it ignores the extensions in the extensions list. (Doesn't install them on startup.) It does seem to start now, though. It just takes a while without any indication whatsoever in any logs about it.

EDIT3: Removing PHP_EXTENSIONS makes the extension-installation work again.

**Comment by Magicalex** [comment]
Can you paste here your docker-compose file please?

**Comment by Magicalex** [comment]
Any news?
