### ISSUE TITLE
sendmail?

### ISSUE THREAD

**Issue by renyuneyun** [mondediefr/docker-flarum#6]
So, under current circumstance, we must use an external smtp service to get mailing work.

How to make it work with `driver=mail` (that is, sending mails from local machine/container)?

**Comment by hardware** [comment]
> So, under current circumstance, we must use an external smtp service to get mailing work.

Or another docker image like https://github.com/hardware/mailserver :innocent:
Or rebuild the docker-flarum image with smtp server in send only mode inside.

https://pkgs.alpinelinux.org/package/v3.5/main/x86_64/msmtp

**Comment by renyuneyun** [comment]
Thanks for your explaination.

Could you provide a sample configuration file (or a link) so I can send mails through it? (Anyway, thanks in advance) After a brief search I couldn't get what I want.
All I need is to send mails directly (without a 3rd-party mail service provider [e.g. gmail]) through the "mail" driver (I suppose it's the `mail()` function of php).
