### ISSUE TITLE
Error 404 on assets

### ISSUE THREAD

**Issue by guiguitcho** [mondediefr/docker-flarum#60]
I am running several containers behind a nginx reverse proxy with SSL encryption. 
I have just simply redirected www.example.com/flarum to the exposed port of docker-flarum container:

```nginx
listen    443;
server_name  example.com;

location /flarum {
    proxy_pass http://127.0.0.1:8888;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
```

After starting docker-compose I had the expected Flarum starting screen.
After that I had a mixed-content error that I fixed by modifying config.php, from:
`'url' => 'http://www.example.com/community'` 
to
`'url' => 'httpS://www.example.com/community'` 

However, now I am facing a 404 error on assets (although they are in assets folder).

I am new to flarum so I don't know what to do. I suspect a nginx rule missing ...

Thanks in advance for any help !

**Comment by Magicalex** [comment]
Any new?
