### ISSUE TITLE
shows private credentials

### ISSUE THREAD

**Issue by awknode** [mondediefr/docker-flarum#66]
This shows private credentials when running in docker and using 'networks' as external. when it shows 'access denied' and throws the exception, no matter what I try, it shows the password to my database and all my info. 

I've tried running bind mounts on php-fpm.conf, www.conf and php.ini after copying them from the image and pasting them back, it still shows all of my information if the database is down. The password is is cleartext form, not encrypted AT ALL. This is a major flaw as I've tried many things to fix it and nothing helps. Very compromising.

**Comment by awknode** [comment]
https://paste.awknode.com/dujihomeye.http

use this as your docker-compose file with an external db that you're connecting to, docker shows everything. you'll have to put your own info in but its cleartext

**Comment by awknode** [comment]
```
    private function safelyBootAndGetHandler()
    {
        try {
            return $this->site->bootApp()->getRequestHandler();
        } catch (Throwable $e) {
            error_log("The database was not available.", 3, "/var/tmp/my-errors.log");
            echo("Database is currently not available. See logs for more details.");
            exit(1);
        }
    }
```

Fixed it with altering the Server.php file in the Http core with this small chunk of code.

**Comment by Magicalex** [comment]
Can you paste content of this file? /mnt/docker/flarum/flarum.env
