### ISSUE TITLE
This will expose your database passwords, use this.

### ISSUE THREAD

**Issue by awknode** [mondediefr/docker-flarum#67]
https://github.com/flarum/core/blob/master/src/Http/Server.php#L48

Modify the server.php in the Http core for this kind of code so it can log to a file and not print out the username, database name, password, etc. I had to shell into docker and get help on this but we were able to find it in 30 minutes and I wrote the code in 2 minutes!

```
    private function safelyBootAndGetHandler()
    {
        try {
            return $this->site->bootApp()->getRequestHandler();
        } catch (Throwable $e) {
            error_log($this->formatBootException($e), 3, "/var/tmp/my-errors.log");
            echo("Database is currently not available. See logs for more details.");
            exit(1);
        }
    }
```

**Comment by Magicalex** [comment]
I do not modify the flarum code, open a issue on the flarum repository [here](https://github.com/flarum/core/issues/new/choose)

**Comment by awknode** [comment]
they are implementing a PR tomorrow for it. all is well.
