### ISSUE TITLE
0.1.0-beta.15

### ISSUE THREAD

**Issue by requilence** [mondediefr/docker-flarum#69]
Thank you for maintaining this docker image!
Could you please make a tag for the recent beta 15?

**Comment by Magicalex** [comment]
tag beta 15 is released [see](https://hub.docker.com/layers/mondedie/flarum/0.1.0-beta.15/images/sha256-4974ea3b20f527bc9d1cd5756595d177a162d296e6cac9fd0214de0fe8c7c956?context=explore)
