### ISSUE TITLE
The PHP extension 'gd' is required.

### ISSUE THREAD

**Issue by pigeon1990** [mondediefr/docker-flarum#7]
Hi, I'm run latest tag in my environment. But I find an error in install page. "The PHP extension 'gd' is required." please help me

**Comment by webeindustry** [comment]
I saw this as well. Switching to 3.5 instead of edge and rebuilding the image did the trick for me.

**Comment by Rodenastyle** [comment]
Same problem here

**Comment by Magicalex** [comment]
ok, I reproduced the problem.
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/gd.so' - Error relocating /usr/lib/libpng16.so.16: inflateValidate: symbol not found in Unknown on line 0
```

**Comment by Magicalex** [comment]
Problem solved.
