### ISSUE TITLE
the rev-maniest doesn't created after php flarum install

### ISSUE THREAD

**Issue by xxxxxliil** [mondediefr/docker-flarum#79]
I using podman not docker run this container

`$ sudo podman run --env-file ./flarum-env.conf --name t --pod t-flarum docker.io/mondedie/flarum `

output:
```
Setting folder permissions
[INFO] Logging to stdout activated
[INFO] First launch, installation...
Installing Flarum...
Connecting to database...done
Writing config file...done
Running migrations...done
Writing default settings...done
Creating admin user flarumadmin...done
Publishing all assets...done
Enabling bundled extensions...done
DONE.
[INFO] End of flarum installation
[INFO] End of startup script. Forum is starting.
^Cstop s6
```
Note: ctrl + c send signal SIGTERM

`$ sudo podman start && sudo podman logs t`

```
[INFO] Setting folder permissions
[INFO] Logging to stdout activated
[INFO] First launch, installation...

                                     
  Command "install" is not defined.  
                                     

[INFO] End of flarum installation
[INFO] End of startup script. Forum is starting.
```

Based on the log output, I found https://github.com/mondediefr/docker-flarum/blob/master/rootfs/usr/local/bin/startup#L78 and found that /flarum/app/public/assets/ rev-manifest.json was not generated after the first successful launch

flarum-env.conf:
```
UID=886
GID=886
LOG_TO_STDOUT=true

#is Mbit
OPCACHE_MEMORY_LIMIT=256
PHP_MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=512M

FLARUM_ADMIN_MAIL=mail
FLARUM_ADMIN_USER=admin
FLARUM_ADMIN_PASS=passwd
#today not support this
FLARUM_ADMIN_PATH=prladm
FORUM_URL=x.y.z/bbs
FLARUM_TITLE=new bb

DB_HOST=127.0.0.1
DB_PORT=3306
DB_NAME=a
DB_USER=a
DB_PASS=a
DB_PREF=a
```

**Comment by Magicalex** [comment]
And your volume?

**Comment by xxxxxliil** [comment]
> And your volume?

I not set volume

**Comment by Magicalex** [comment]
You need to set up volume 

```yml
      - /mnt/docker/flarum/assets:/flarum/app/public/assets
      - /mnt/docker/flarum/extensions:/flarum/app/extensions
      - /mnt/docker/flarum/nginx:/etc/nginx/flarum
```

Otherwise the data will not be persistent when the container starts.

**Comment by xxxxxliil** [comment]
> You need to set up volume
> 
> ```yaml
>       - /mnt/docker/flarum/assets:/flarum/app/public/assets
>       - /mnt/docker/flarum/extensions:/flarum/app/extensions
>       - /mnt/docker/flarum/nginx:/etc/nginx/flarum
> ```
> 
> Otherwise the data will not be persistent when the container starts.

run args add `--volume /var/local/lib/ctr-flarum/main/assets:/flarum/app/public/assets --volume /var/local/lib/ctr-flarum/main/extensions:/flarum/app/extensions --volume /var/local/lib/ctr-flarum/main/nginx:/etc/nginx/flarum --volume /var/local/lib/ctr-flarum/main/storage:/flarum/app/storage`

but rev-maniest still doesn't created

**Comment by xxxxxliil** [comment]
rev-manifest.json can only be generated after a visit

**Comment by Magicalex** [comment]
Ok, I test as soon as possible.

**Comment by xxxxxliil** [comment]
@Magicalex
