### ISSUE TITLE
how to correctly setup the reverse proxy

### ISSUE THREAD

**Issue by fyears** [mondediefr/docker-flarum#8]
Hi,

I do not fully understand the step 3: [reverse proxy](https://github.com/mondediefr/docker-flarum/wiki/Reverse-proxy-example).

1. Should I provide these 4 files by myself? 

    ```
    - /mnt/docker/nginx/sites-enabled:/sites-enabled
    - /mnt/docker/nginx/conf:/conf.d
    - /mnt/docker/nginx/log:/var/log/nginx
    - /mnt/docker/nginx/certs:/certs
    ```

2. Is there a separated `docker-compose.yml` for nginx?

    (I guess not, but ask it here)

3. Should I directly run `docker exec -ti nginx ngxproxy` (for reverse proxy) then `docker-compose up -d` (step 4 in `README.md`) in the same terminal? Or in separated terminals?

Thank you so much!

**Comment by osixia** [comment]
Hello,
if you want to put a reverse proxy in front of your containers take a look at traefik:
https://github.com/containous/traefik

**Comment by fyears** [comment]
@osixia  Hi, thank you. But all I need is a flarum running in docker for my php/flarum development. I am new to Docker and it seems that the requirements are more complex than I thought. :-(

**Comment by Magicalex** [comment]
> Should I provide these 4 files by myself?
It's not a files but directory

> Is there a separated docker-compose.yml for nginx?
no

> Should I directly run docker exec -ti nginx ngxproxy (for reverse proxy) then docker-compose up -d (step 4 in README.md) in the same terminal? Or in separated terminals?
I don't understand your question, why do you want to use a separated terminal. I think the example is pretty explicit.

**Comment by fyears** [comment]
@Magicalex Thank you for your explanation.

Now I am able to access the local flarum here.

I would like to explain what I did not understand before.

1. I know they are four directories now. I was unsure whether I should prepare the files/directories. 

    Now I know docker creates them automatically. 

2. In `README.md`, step 2 provides a `docker-compose.yml` containing `flarum` and `mariadb`, step 3 also provides a `docker-compose.yml` containing `nginx` configuration. 

    I did not realized that they should be written **together**, instead of being in separated `*.yml` files. 

3. I should run `docker-compose up -d` firstly, and **after that** run `docker exec -ti nginx ngxproxy`. 

    I ran `docker exec -ti nginx ngxproxy` **before** running `docker-compose up -d`, then I met the error `Error response from daemon: No such container: nginx`. That's why I got confused.

 Seriously, it was confusing. But now I know what's going on.
