### ISSUE TITLE
A question about custom Nginx configuration

### ISSUE THREAD

**Issue by xxxxxliil** [mondediefr/docker-flarum#84]
I checked https://github.com/mondediefr/docker-flarum/blob/fc0944c7d5bcdec0d4387d097a6eb341563e3ca8/rootfs/etc/nginx/nginx.conf#L60 and https://github.com/mondediefr/docker-flarum/blob/fc0944c7d5bcdec0d4387d097a6eb341563e3ca8/rootfs/usr/local/bin/startup#L68-L75, and if nginx.conf#L60 is replaced with the following configuration file fragment, can remove startup#L68-L75.

```
    #Don't assume /etc/nginx/flarum/custom-vhost-flarum.conf always exists
    #/etc/nginx/flarum/custom-vhost-flarum.conf is file
    if (-f /etc/nginx/flarum/custom-vhost-flarum.conf){
        include /etc/nginx/flarum/custom-vhost-flarum.conf;
    }
```

**Comment by xxxxxliil** [comment]
> @xxxxxliil Probably you meant lines 68-75? In startup script.

Yes, lines 68-75

**Comment by xxxxxliil** [comment]
@Magicalex

**Comment by Magicalex** [comment]
Yes I am agree with this solution `if (-f /etc/nginx/flarum/custom-vhost-flarum.conf)`
