### ISSUE TITLE
flarum install need mysql command

### ISSUE THREAD

**Issue by xxxxxliil** [mondediefr/docker-flarum#91]
![image](https://user-images.githubusercontent.com/48526227/120143879-8bc45880-c213-11eb-9b30-c10c4325e235.png)

**Comment by xxxxxliil** [comment]
I'm currently testing my branch, but I haven't changed anything related to the flarum installation

**Comment by xxxxxliil** [comment]
using origin image:
![image](https://user-images.githubusercontent.com/48526227/120145338-e8c10e00-c215-11eb-8f61-f7250220ad54.png)

**Comment by Magicalex** [comment]
fix in v1.0.1 of flarum
