### ISSUE TITLE
A question about nginx.conf

### ISSUE THREAD

**Issue by xxxxxliil** [mondediefr/docker-flarum#93]
https://github.com/mondediefr/docker-flarum/blob/74589ee3ec5d1f3255e8e56b04aa9d702cd7ed74/rootfs/etc/nginx/nginx.conf#L59
What is the advantage of doing this over using if ( -f )?

**Comment by Magicalex** [comment]
You can't include the file not exist even with if

**Comment by xxxxxliil** [comment]
> You can't include the file if it not exist even with `if`

Now this change?
