### ISSUE TITLE
Recent tags are missing

### ISSUE THREAD

**Issue by arthurtemple** [mondediefr/docker-flarum#97]
Hi,

Thanks for maintaining this repo.

I see that you recently updated the image to use "release" versions of Flarum 1.0.0 up to 1.0.2.
However there are no tags/releases here matching these versions, hence no corresponding images were pushed to Docker Hub.

This means instructions in [the upgrade guide](https://github.com/mondediefr/docker-flarum/blob/master/UPGRADE.md) lead to an error.

Is there a reason for not pushing tags to this repo?

**Comment by Magicalex** [comment]
Indeed, works in progress

**Comment by arthurtemple** [comment]
Nice! Thanks a lot.

**Comment by Magicalex** [comment]
@arthurtemple Done
